name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment:
      name: github-pages
      url: https://werte.jardas.de/
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
